services:
  - type: web
    name: spring-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    autoDeploy: true

  - type: web
    name: react-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    plan: free
    autoDeploy: true
