services:
  - type: web
    name: spring-backend
    env: docker
    dockerfilePath: Backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    autoDeploy: true

  - type: web
    name: react-frontend
    env: docker
    dockerfilePath: Frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
    plan: free
    autoDeploy: true
