# Etapa 1: Compila el proyecto
FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: Ejecuta el proyecto
FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

# 🚨 Agregar esta línea
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
